version: "4.16"

services:
  documentservice:
    container_name: documentservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5011:80
    expose:
      - "5001"
      - "5000"
    networks:
      - backend
    restart: always
  pdfservice:
    container_name: pdfservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5012:80
    expose:
      - "5002"
      - "5000"
    networks:
      - backend
    restart: always
  storageservice:
    container_name: storageservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5013:80
    expose:
      - "5003"
      - "5000"
    networks:
      - backend
    restart: always
    
networks:
  backend:
    external: true
    ipam:
      driver: bridge
      config:
      - subnet: 172.19.0.0/16
