version: "4.16"

services:
  documentservice:
    container_name: documentservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    restart: always
  pdfservice:
    container_name: pdfservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    restart: always
  storageservice:
    container_name: storageservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    restart: always
